In [11]:
import numpy as np

In [12]:
a = [i for i in range(10)]

In [13]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
b = np.array(a)

In [15]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.array([i for i in range(10)])

In [19]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [21]:
b = np.array(c)

In [22]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
type(b)

numpy.ndarray

In [24]:
b = np.array(a, dtype = float)

In [25]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]

In [26]:
b = np.array(a, dtype = int)

In [27]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.array(a, dtype = float)

In [29]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [32]:
b = np.array(a, dtype = str)

In [33]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [34]:
a = ['abc', 1, 2, 3]

In [36]:
b.dtype

dtype('<U3')

In [37]:
a = [0, 1, 2, 3.125]

In [38]:
b = np.array(a)

In [39]:
b

array([0.   , 1.   , 2.   , 3.125])

In [41]:
b.dtype

dtype('float64')

In [42]:
b[0]

0.0

In [43]:
b[1]

1.0

In [44]:
b[2]

2.0

In [45]:
b[3]

3.125

In [46]:
b.ndim

1

In [47]:
b.shape

(4,)

In [48]:
### 20 array

In [50]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 
              [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
b.shape

(3, 10)

In [52]:
b.size

30